gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = "gallery"

urlpatterns = [
    url(r'^gallery', views.gallery, name='gallery'),
    url(r'^search/', views.search_results, name='search'),
    url(r'^location/(?P<location>\w+)/', views.image_location, name='location'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views
app_name = "main"
urlpatterns = [
    path("", views.index, name = "index"),
]

photomania/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls", namespace="main")),
    path("", include("gallery.urls", namespace="gallery")),
]

gallery/models.py
from django.db import models

# Create your models here.


class Location(models.Model):
    """
    Location class to define location model
    """
    name = models.CharField(max_length=60)

    @classmethod
    def get_locations(cls):
        locations = Location.objects.all()
        return locations

    def __str__(self):
        return self.name

    @classmethod
    def update_location(cls, id, value):
        cls.objects.filter(id=id).update(image=value)

    def save_location(self):
        self.save()

    def delete_location(self):
        self.delete()

#category choices
category_choices = (
    ("NATURE", "nature"),
    ("CULTURE", "culture"),
    ("SCIENCE", "science"),
)
class Category(models.Model):
    """
    Category class to define category model
    """
    name = models.CharField(max_length=50, choices=category_choices)

    def __str__(self):
        return self.name

    def save_category(self):
        self.save()

    def delete_category(self):
        self.delete()

class Image(models.Model):
    """
    image class to define image model
    """
    image = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=60)
    description = models.TextField()
    author = models.CharField(max_length=40, default='admin')
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    @classmethod
    def filter_by_location(cls, location):
        image_location = Image.objects.filter(location__name=location).all()
        return image_location

    @classmethod
    def update_image(cls, id, value):
        cls.objects.filter(id=id).update(image=value)

    @classmethod
    def get_image_by_id(cls, id):
        image = cls.objects.filter(id=id).all()
        return image

    @classmethod
    def search_by_category(cls, category):
        images = cls.objects.filter(category__name__icontains=category)
        return images

    def __str__(self):
        return self.name

    def save_image(self):
        self.save()

    def delete_image(self):
        self.delete()

    class Meta:
        ordering = ['date']

homepage/models.py
from django.db import models

# Create your models here.
#

gallery/views.py
from django.shortcuts import render
from .models import Category
# Create your views here.
from .models import Image, Location

def image_location(request, location):
    """
    function to filter by location
    """
    images = Image.filter_by_location(location)
    print(images)
    return render(request, 'location.html', {'location_images': images})

def search_results(request):

    if 'image' in request.GET and request.GET["image"]:
        search_term = request.GET.get("image")
        searched_images = Image.search_by_category(search_term)
        message = f"{search_term}"

        return render(request, 'search_results.html',{"message":message,"images": searched_images})

    else:
        message = "You haven't searched for any image"
        return render(request, 'search_results.html',{"message":message})

def gallery(request):
    images = Image.objects.all()
    locations = Location.get_locations()
    print(locations)
    return render(request, 'gallery.html', {'images': images[::-1], 'locations': locations})

homepage/views.py
from django.shortcuts import render
from gallery.models import Location,Image,Category
# Create your views here.
def index(request):
    return render(request, "index.html")

gallery/templates/gallery.html
{% extends 'base.html' %}


{% block content %}
{% include "navbar.html" %}

<style>
    body {
        background-color: #e9edc9;
    }
    
</style>
<div class="card text-center" style="margin-top: 6rem;">
  
    </div>
    <div class="card-body">
      <h5 class="card-title" style="font-family: 'Gluten', cursive;
      font-family: 'Kalam', cursive;"></h5>
      <p class="card-text" style="font-family: 'Gluten', cursive;
      font-family: 'Kalam', cursive;">Welcome to PhotoMania.Pictures are a powerful way to express out ideas rather abstract or real.Check out some of my pictures on my loved topics.You can also copy the image url to download it to your personal computer or phone!</p>
   
      <div  id="bottom" class="btn btn-secondary" style="font-family: Verdana, Geneva, Tahoma, sans-serif; " >Scroll to start viewing!</div>
      </div>
    
    <div class="card-footer text-muted">
   </div>
    </div>
  </div>


  <!--gallery-->
  <div class="row" style="margin-top: 3rem;">
    <div class="col-md-7">
        <h3 style="font-family: 'Gluten', cursive;
        font-family: 'Kalam', cursive;">Gallery</h3>
    </div>
</div>

    <hr>

  </div>

    <div class="container">
    <!-- <div class="row align-items-center">-->
      <div class="row">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" style="margin-left: 10rem; margin-bottom: 3rem;  display: inline-block;">
 <br>
     
      
      {% for image in images %}
      <span id="locations" style="margin: 2rem; border: 2rem; padding: 10px;">
        {% for location in locations %}
            <a class="btn btn-outline-info btn-sm" id="btn"
               href="/location/{{location.name}}">{{location.name}}</a>
        {%endfor%}
     </span>
    
 
    <div class="card"  data-toggle="modal" data-target="#{{image.id}}">
          <img src="{{image.image.url}}" alt="{{image.name}}" class="card-img">
</div>

      <div class="modal fade " id="{{image.id}}" tabindex="-1" role="dialog"
           aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-md" role="document">
              <div class="modal-content modalcard">
                  <div class="modal-header">
                      <h5 class="modal-title" id="imageheader">{{image.name}}</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <img src="{{image.image.url}}" alt="{{image.name}}" class="img-fluid">
                      <p class="imgdesc text-center">{{image.description}}</p>
                      <span class="btn btn-sm btn-outline-success">{{image.category}}</span> <a
                          href="/location/{{image.location}}" class="btn btn-sm btn-outline-info">{{image.location}}</a>
                  </div>
                  <div class="modal-footer">
                      <input class="form-control input-lg" type="text"
                             value="{{image.image.url}}" id="{{image.id}}.url">
                      <button class="btn btn-success btn-sm" onclick="copyLink('{{image.id}}.url')">Copy</button>
                      <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal">Close
                      </button>
                  </div>
              </div>
          </div>
        
      </div>
      {% endfor %}
  </div>
</div>
</div>
<script>
    function top() {
    document.getElementById( 'top' ).scrollIntoView();    
};

function bottom() {
    document.getElementById( 'bottom' ).scrollIntoView();
    window.setTimeout( function () { top(); }, 2000 );
};

bottom();
</script>


</div>

  {% endblock %}

gallery/templates/location.html
{% extends 'base.html' %}
{% block content %}
{% include "navbar.html" %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gluten:wght@600&family=Kalam&display=swap" rel="stylesheet">
<style>
    body {
        background-color: #e9edc9;
    }
</style>
<div class="container" style="margin-top: 6rem;">
    <h2 style="font-family: 'Gluten', cursive;
    font-family: 'Kalam', cursive;">Items with Location</h2>
    <hr style="margin: 2rem;">

    {% if location_images %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3" style="margin-left: 14rem; margin-bottom: 3rem;  display: inline-block;">
 
     
      
        {% for image in location_images %}
        <div class="row">
            <div class="col-12 col-sm-8" style="">
                <div class="btn btn-primary" style="">{{image.category}}</div>
            </div>
            <div class="col-6 col-sm-2" >
                <div class="btn btn-primary" style="margin-right: 4rem;">{{image.name}}</div>
            </div>
          </div>
          
        <div class="card" data-toggle="modal" data-target="#{{image.id}}">
            <img src="{{image.image.url}}" alt="{{image.name}}" class="card-img">
        </div>
        <div class="modal fade " id="{{image.id}}" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content modalcard">
                    <div class="modal-header">
                        <h5 class="modal-title d-block mx-auto" id="exampleModalLongTitle">{{image.name}}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <img src="{{image.image.url}}" alt="{{image.name}}" class="img-fluid">
                        <p>{{image.description}}</p>
                        <span class="btn btn-sm btn-outline-success">{{image.category | title}}</span> <a href="/location/{{image.location}}" class="btn btn-sm btn-outline-info">{{image.location}}</a>
                    </div>
                    <div class="modal-footer">
                        <input class="form-control input-lg" type="text"
                               value="{{image.image.url}}" id="{{image.id}}.url">
                        <button class="btn btn-success btn-sm" onclick="copyLink('{{image.id}}.url')">Copy</button>
                        <button type="button" class="btn btn-outline-danger btn-sm" data-dismiss="modal">Close
                        </button>
                    </div>
                </div>
            </div>
        </div>


        {% endfor %}
    </div>
    {% endif %}

</div>
{% endblock %}

gallery/templates/search_results.html
{%extends 'base.html'%}
{% block content %}
<div class="container">
  <body style="background-color:#E6E6FA">

  <div class="row">
    {% if images%}
      <h2>Found {{ images|length }} of searched term {{message}}</h2>
    {% else %}
      <h2> Found 0 images for the search term {{message}}</h2>
    {% endif %}

  </div>

  <div class="row">

  {% if images %}
    {% for image in images %}
      <div class="col-sm-4">
        <img src="{{image.image.url}}"  class="img-responsive" alt="">
      </div>
    {% endfor %}
  {% endif %}
  </div>
</body>
</div>
{% endblock %}

homepage/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" %}


<!--homepage-->
<style>
  .container {
    position: relative;
    text-align: center;
    color: white;
  }
  
  .bottom-left {
    position: absolute;
    bottom: 8px;
    left: 16px;
  }
  
  .top-left {
    position: absolute;
    top: 8px;
    left: 16px;
  }
  body {
    background-color: #e9edc9;
  }
  .top-right {
    position: absolute;
    top: 8px;
    right: 16px;
  }
  
  .bottom-right {
    position: absolute;
    bottom: 8px;
    right: 16px;
  }
  
  #centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    border: white;
    background-color: white;
    border-radius: 10%;
   
  }
  </style>
<div class="text-center">
  <h3 style="margin-top: 3rem; color: black; font-family: 'Gluten', cursive;
  font-family: 'Kalam', cursive;">PhotoMania ~ Get to feel how photography can change our perception into things</h3>
</div>
  <div class="container" style="margin-top: 7rem; margin-bottom: 7rem;">
    <img src="https://images.unsplash.com/photo-1637448096758-95360e65e72f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIyfHRvd0paRnNrcEdnfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60" alt="Snow" style="width:100%;">
<a href="{% url 'gallery:gallery' %}" id="centered">View<i class="fas fa-eye"></i></a>
  </div><br><br><br>
  
{% endblock %}

homepage/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" style="font-family: 'Gluten', cursive;
      font-family: 'Kalam', cursive;" href="{% url 'main:index' %}">PhotoMania</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gallery:gallery' %}">Gallery</a>
          </li>
         <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Science</a></li>
              <li><a class="dropdown-item" href="#">Nature</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Culture</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
          </li>
        </ul>-->
        <form class="d-flex" action="/search" style="margin-left: 5rem;">
          <input class="form-control me-2" type="search" placeholder="Search by category" aria-label="Search" name="search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  
  

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gluten:wght@600&family=Kalam&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
<title></title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2"></h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>